name: Fuzzy Lime Pizza Napkin
favicon: null
layout_spectrum: 0.2551086733583361
typography_spectrum: 0.5614327352959663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11595333344303071
  lightness: 0.939007923938334
  saturation: 0.29456730955280364
  rhythmicContrast: 0.6774622008670121
purpose: []
